env:
  - name: _JAVA_OPTIONS
    value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx1024m
pipelines:
  pullRequest:
    pipeline:
      agent:
        image: maven
      stages:
      - name: build
        steps:
        - sh: mvn versions:set -DnewVersion=$PREVIEW_VERSION
          name: set-version
        - sh: mvn install
          name: mvn-install
        - sh: skaffold version
          name: skaffold-version
        - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
          name: container-build
      - name: postBuild
        steps:
        - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
          name: post-build
      - name: promote
        steps:
        - dir: charts/preview
          steps:
          - sh: make preview
            name: make-preview
          - sh: jx preview --app $APP_NAME --dir ../..
            name: jx-preview
  release:
    pipeline:
      agent:
        image: maven
      stages:
      - name: setup
        steps:
        - groovy: git 'https://REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME.git'
          when: "prow"
        - sh: git checkout master
          comment: ensure we're not on a detached head
          when: "!prow"
        - sh: git config --global credential.helper store
          when: "!prow"
        - sh: jx step git credentials
          when: "!prow"
      - name: setVersion
        steps:
        - sh: echo \$(jx-release-version) > VERSION
          name: next-version
          comment: so we can retrieve the version in later steps
        - sh: mvn versions:set -DnewVersion=\$(cat VERSION)
          name: set-version
        - sh: jx step tag --version \$(cat VERSION)
          name: tag-version
      - name: build
        steps:
        - sh: mvn clean deploy
          name: mvn-deploy
        - sh: skaffold version
          name: skaffold-version
        - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
          name: container-build
        - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
          name: post-build
      - name: postBuild
        steps:
        - groovy: always
          when: "!prow"
          steps:
          - groovy: "cleanWs()"
      - name: promote
        steps:
        - dir: charts/REPLACE_ME_APP_NAME
          steps:
          - sh: jx step changelog --version v\$(cat ../../VERSION)
            name: changelog
          - comment: release the helm chart
            sh: jx step helm release
            name: helm-release
          - comment: promote through all 'Auto' promotion Environments
            sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
            name: jx-promote